package schema

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

// FieldSpec describes a single field from the schema YAML.
type FieldSpec struct {
	Name          string `yaml:"name"`
	Type          string `yaml:"type"`
	Primary       bool   `yaml:"primary"`
	Auto          bool   `yaml:"auto"`          // generated by DB or timestamp — skip from CreateParams
	AutoUpdate    bool   `yaml:"auto_update"`   // → field = now() in UPDATE SET (requires auto: true)
	AutoIncrement bool   `yaml:"auto_increment"` // → field = field+1 in UPDATE SET (requires auto: true)
	Nullable      bool   `yaml:"nullable"`
	Required      bool   `yaml:"required"`
	Default       string `yaml:"default"`
}

// Schema is the top-level schema YAML structure.
type Schema struct {
	Module     string      `yaml:"module"`
	Table      string      `yaml:"table"`
	ScopeBy    string      `yaml:"scope_by"`    // field name → ListByUserID scoped query
	OwnerField string      `yaml:"owner_field"` // field name → ownership check in Update/Delete
	Fields     []FieldSpec `yaml:"fields"`
}

// Parse reads and validates a schema YAML file.
func Parse(path string) (*Schema, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("schema: read %q: %w", path, err)
	}

	var s Schema
	if err := yaml.Unmarshal(data, &s); err != nil {
		return nil, fmt.Errorf("schema: parse %q: %w", path, err)
	}

	if err := validate(&s); err != nil {
		return nil, fmt.Errorf("schema: %w", err)
	}

	return &s, nil
}

func validate(s *Schema) error {
	if s.Module == "" {
		return fmt.Errorf("module name is required")
	}
	if s.Table == "" {
		s.Table = s.Module + "s" // sensible default
	}
	if len(s.Fields) == 0 {
		return fmt.Errorf("at least one field is required")
	}

	validTypes := map[string]bool{
		"uuid": true, "string": true, "int": true, "int64": true,
		"float": true, "bool": true, "timestamp": true, "json": true, "string[]": true,
	}
	for _, f := range s.Fields {
		if f.Name == "" {
			return fmt.Errorf("all fields must have a name")
		}
		if !validTypes[f.Type] {
			return fmt.Errorf("field %q has unsupported type %q (valid: uuid, string, int, int64, float, bool, timestamp, json, string[])", f.Name, f.Type)
		}
	}
	return nil
}
